plot1 = ggplot(train_2, aes(Unemployment_percentage, residuals(model2))) + geom_point() + geom_smooth()
plot2=ggplot(train_2, aes(HDI, residuals(model2))) + geom_point() + geom_smooth()
plot3=ggplot(train_2, aes(Population_Density_per_sq_km, residuals(model2))) + geom_point() + geom_smooth()
plot4=ggplot(train_2, aes(Weapons_per_100_persons, residuals(model2))) + geom_point() + geom_smooth()
plot5=ggplot(train_2, aes(Per_Capita_Income, residuals(model2))) + geom_point() + geom_smooth()
plot6=ggplot(train_2, aes(Gini_Coefficient, residuals(model2))) + geom_point() + geom_smooth()
plot7=ggplot(train_2, aes(Literacy_Rate, residuals(model2))) + geom_point() + geom_smooth()
plot8=ggplot(train_2, aes(Happiness_Index, residuals(model2))) + geom_point() + geom_smooth()
suppressMessages({grid.arrange(plot1,plot2,plot3,plot4,plot5,plot6,plot7,plot8)})